### ISSUE TITLE
Not allowed to load resource: file:///storage/emulated/0/.....

### ISSUE THREAD

**Issue by krabouilleur** [WebsiteBeaver/android-document-scanner#15]
Hi,

I have a webview. When I click on a button in the webview, the native app launch de document scanner.

The "success handler" return to me a path file : "file:///storage/emulated/0/Android/data/com.xxx/files/Pictures/DOCUMENT_SCAN_0_....jpg

On native app I can show the image in a ImageView.

but I can't show the image in the webview with an <img> tag

<img src="file:///storage/emulated/0/Android/data/com.xxx/files/Pictures/DOCUMENT_SCAN_0_xxxxx.jpg">

Chrome response: 
"Not allowed to load local resource: file:///storage/emulated/0/Android/data/com.xxx/files/Pictures/DOCUMENT_SCAN_0_xxxxxxx.jpg

And in my native app I've this settings:
```
myWebView.getSettings().setAllowContentAccess(true);
myWebView.getSettings().setAllowFileAccess(true);
myWebView.getSettings().setAllowFileAccessFromFileURLs(true);
myWebView.getSettings().setAllowUniversalAccessFromFileURLs(true);
```

What's wrong ?

**Comment by dmarcs** [comment]
I'm not sure, maybe you need a uses-permission to do that. Are you able to load any files from your device?
