### ISSUE TITLE
Increase Cropper size

### ISSUE THREAD

**Issue by PPetka** [WebsiteBeaver/android-document-scanner#17]
Hey

Is there a way to increase cropper size? When adjusting corner I am covering almost all the cropper view with my tumb, I need to move my head around to see what's under that. Is there a way easy (or in a hacky way) to adjust it? 
Btw, great library!

Greetings!

**Comment by dmarcs** [comment]
You can increase the cropper size by editing these variables https://github.com/WebsiteBeaver/android-document-scanner/blob/master/documentscanner/src/main/res/values/dimens.xml

```
<dimen name="cropper_corner_radius">25px</dimen>
<dimen name="cropper_selected_corner_radius_magnification">4px</dimen>
<dimen name="cropper_selected_corner_background_magnification">5px</dimen>
```
