### ISSUE TITLE
Error opening camera: Failed to find configured root that contains [filePath]

### ISSUE THREAD

**Issue by ben04** [WebsiteBeaver/android-document-scanner#20]
Hi!

I'm trying to integrate this library into an existing app but keep getting this error message:
`V/documentscannerlogs: error - error opening camera: Failed to find configured root that contains /storage/emulated/0/Android/data/my.app.package/files/Pictures/DOCUMENT_SCAN_0_20230131_0958198508389360123480978.jpg`

When I run the demo from this repo, it works fine. However, I've followed the instructions to the point, so I'm clueless where the error comes from. Do you have an idea?

**Comment by dmarcs** [comment]
maybe there's something in your AndroidManifest.xml that stops this from working

**Comment by GMRemie** [comment]
@ben04 You need to check how you have your file provider set up. 

Reference the app manifest in the demo for a better example


**AndroidManifest.xml**
`        <provider
            android:name="com.websitebeaver.documentscanner.DocumentScannerFileProvider"
            android:authorities="${applicationId}.DocumentScannerFileProvider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />
        </provider>`

**xml/file_paths.xml**
`<paths>
    <external-files-path name="images" path="Pictures" />
</paths>`

Hope this helps!

**Comment by shaifu** [comment]
I am experiencing the same issue as @ben04. I have tried the solution but no success.
