### ISSUE TITLE
Skipping middle screen

### ISSUE THREAD

**Issue by PPetka** [WebsiteBeaver/android-document-scanner#23]
Hey
Is there a way to skip this screen and go directly to the picking corners one?
The whole process starts from taking photo screen, then it goes to this confirmation and and then to the last, picking corners screen. I would like to skip the second part as it brings no additional value.
![Screenshot_20230203-152824](https://user-images.githubusercontent.com/29818981/216628688-c2219aa8-2b32-4776-ba96-d47282408863.jpg)

Thank you.

**Comment by dmarcs** [comment]
There isn't a way to skip that screen now. I would need to use CameraX in order to accomplish this, but I don't think it's worth it.
