### ISSUE TITLE
Possible to add Share and Backbtn on Preview Page?

### ISSUE THREAD

**Issue by Marow** [WebsiteBeaver/android-document-scanner#25]
Hi,

i tried to add a share button and want also a "back" button to start on the last page where is just the preview.
I found the Place and tried to add it, but what can i use as `uri` for the `intent.putExtra(Intent.EXTRA_STREAM, uri)` of intent?

Here is full code

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        // cropped image
        croppedImageView = findViewById(R.id.cropped_image_view)

        shareBtn = findViewById(R.id.shareBtn)
        shareBtn.setOnClickListener {
            val intent= Intent(Intent.ACTION_SEND)
            //intent.putExtra(Intent.EXTRA_TEXT,"Hey Check out this Great app:")
            //intent.type="text/plain"
            intent.putExtra(Intent.EXTRA_STREAM, uri)
            intent.type = "application/pdf"
            startActivity(Intent.createChooser(intent, null))
        }

        // start document scan
        documentScanner.startScan()
}
```

I just added the ShareBtn, also in layout but i get errors cause i didnt find an uri for the EXTRA_STREAM... 

And is it also possible to add a function "back to start" there with a button too?
I am new to doing app things, so hope someone can help 👍

**Comment by dmarcs** [comment]
Interesting ideas, but I think it's better without these options.
