### ISSUE TITLE
Landscape is not working. The state is not saved

### ISSUE THREAD

**Issue by jachzen** [WebsiteBeaver/android-document-scanner#6]
Nice work. But when staying in landscape the behaviour of the library is wrong.

simplest solution lock the orientation

        <activity
            android:name=".DocumentScannerActivity"
            android:screenOrientation="portrait"
            android:configChanges="orientation"
            android:theme="@style/Theme.FullScreen" />

**Comment by dmarcs** [comment]
can you include a screenshot showing what you mean? I tested landscape, and it seems to work.

**Comment by dmarcs** [comment]
fixed in 1.0.5 https://github.com/WebsiteBeaver/android-document-scanner/commit/81420c8cdfb35b2a972dff4b6ec592bfb3e53604

On some Android phones changing orientation (portrait to landscape for example) causes the app to crash because it restarts the Activity
